version: "3"

services:
  app:
    container_name: app
    build: 
      context: ./node
    tty: true
    command: node index.js
    volumes:
      - ./node:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet
    
  db:
    container_name: db
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_PASSWORD=1524
      - MYSQL_ROOT_PASSWORD=1524
      - MYSQL_USER=jose
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3


  nginx:
    container_name: nginx
    build:
      context: ./nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    networks:
      - appnet
    

networks:
  appnet:
    driver: bridge